//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkHardwareEmulator.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaboratoryWork
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int UserID { get; set; }
        public Nullable<int> SuccessRateLab { get; set; }
        public System.DateTime DateWorkEnding { get; set; }
    
        public virtual User User { get; set; }
    }
}
